name: Update Memes-metadata.json List

on:
  workflow_run:
    workflows: ["update-memes.json"]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install image-size node-fetch

      - name: Generate metadata
        run: node get-meme-metadata.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add memes-metadata.json
          git commit -m "Updated memes-metadata.json"
          git push
