name: Update Memes.json List

permissions:
  contents: write

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch Google Sheet meme URLs
        run: |
          curl -L \
            "https://opensheet.elk.sh/1xKWkXyEttoF4blJYAs1ehGZ9S2wSzNmG8a5CMnuHmds/Sheet1" \
            -o sheet.json

      - name: Build memes.json
        run: |
          # 1. Build local file list as a JSON array of strings
          ls memes | jq -R '. | "memes/" + .' | jq -s '.' > local.json

          # 2. Extract "url" property from Google Sheet rows
          jq -r '.[].url' sheet.json | jq -R -s 'split("\n")[:-1]' > remote.json

          # 3. Merge arrays into final JSON list
          jq -s 'add' local.json remote.json > memes.json

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Updated memes.json"
          file_pattern: memes.json
